name: Tests
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Run linter and package audit
    container:
      image: node:20-slim
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: |
          yarn -v
          yarn

      - name: Lint
        run: |
          yarn run lint

      - name: Audit Production Dependencies
        run: yarn audit --groups dependencies

  test:
    runs-on: ubuntu-20.04
    name: Run tests
    container:
      image: node:20-slim
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: |
          yarn -v
          yarn

      - name: Test
        run: yarn run test
